const SHEETS = { records: 'SALES_LOG', markets: 'MARKETS', services: 'SERVICES', settings: 'SETTINGS' };
const RECORD_HEADERS = ['Entry_ID','Timestamp','Service_Date','Region','Country','Country_Code','Service_Key','Service_Name','Service_Category','Duration_Minutes','Quantity','Unit_Price','Currency','Gross_Sales','Commission_Rate','Tranquilitas_Revenue','Partner_Payout','Booking_Source','Channel','Entered_By','Status','Review_Reason','Notes'];
function doPost(e) { try { const req = JSON.parse(e.postData && e.postData.contents || '{}'); const action = req.action; if (['CREATE_RECORDS','UPDATE_RECORD'].includes(action)) validateToken_(req.token); const data = route_(action, req.payload || {}); return json_({ success: true, data, message: 'Request completed' }); } catch (err) { return json_({ success: false, error: { code: err.code || 'REQUEST_FAILED', message: err.publicMessage || err.message || 'The request could not be completed.' } }); } }
function route_(action, payload) { if (action === 'GET_RECORDS') return mapSheet_(SHEETS.records); if (action === 'GET_MARKETS') return mapSheet_(SHEETS.markets); if (action === 'GET_SERVICES') return mapSheet_(SHEETS.services); if (action === 'CREATE_RECORDS') return createRecords_(payload); if (action === 'UPDATE_RECORD') return updateRecord_(payload); throw publicError_('UNKNOWN_ACTION','Unknown dashboard action.'); }
function createRecords_(payload) { const records = payload.records || []; if (!Array.isArray(records) || !records.length) throw publicError_('EMPTY_BATCH','Add at least one record before submitting.'); const markets = activeByCode_(mapSheet_(SHEETS.markets)); const services = serviceMap_(mapSheet_(SHEETS.services)); const rows = records.map((record) => buildRow_(record, markets, services)); SpreadsheetApp.getActive().getSheetByName(SHEETS.records).getRange(lastRow_(), 1, rows.length, RECORD_HEADERS.length).setValues(rows); const summary = rows.reduce((s, r) => ({ records: s.records + 1, serviceVolume: s.serviceVolume + Number(r[10]), grossSales: s.grossSales + Number(r[13]), tranquilitasRevenue: s.tranquilitasRevenue + Number(r[15]), partnerPayout: s.partnerPayout + Number(r[16]), countries: s.countries.includes(r[4]) ? s.countries : s.countries.concat(r[4]) }), { records: 0, serviceVolume: 0, grossSales: 0, tranquilitasRevenue: 0, partnerPayout: 0, countries: [] }); return { created: rows.map(rowToRecord_), batchId: payload.idempotencyKey || Utilities.getUuid(), summary }; }
function updateRecord_(payload) { if (!payload.id) throw publicError_('MISSING_ID','Entry ID is required.'); const sheet = SpreadsheetApp.getActive().getSheetByName(SHEETS.records); const values = sheet.getDataRange().getValues(); const rowIndex = values.findIndex((row, index) => index > 0 && row[0] === payload.id); if (rowIndex < 1) throw publicError_('NOT_FOUND','The selected record was not found.'); const current = rowToRecord_(values[rowIndex]); const updates = Object.assign({}, current, payload.updates || {}); const markets = activeByCode_(mapSheet_(SHEETS.markets)); const services = serviceMap_(mapSheet_(SHEETS.services)); const rebuilt = buildRow_(updates, markets, services, current.id, current.timestamp); sheet.getRange(rowIndex + 1, 1, 1, RECORD_HEADERS.length).setValues([rebuilt]); return { record: rowToRecord_(rebuilt) }; }
function buildRow_(record, markets, services, existingId, existingTimestamp) { const market = markets[record.countryCode]; if (!market) throw publicError_('INVALID_COUNTRY','Choose an active market before submitting.'); const service = services[record.countryCode + '|' + record.serviceKey]; if (!service) throw publicError_('INVALID_SERVICE','The selected service is not available for ' + market.Country + '.'); const quantity = Number(record.quantity); if (!Number.isInteger(quantity) || quantity <= 0) throw publicError_('INVALID_QUANTITY','Quantity must be a positive whole number.'); const unitPrice = record.unitPriceOverride != null && record.unitPriceOverride !== '' ? Number(record.unitPriceOverride) : Number(service.Unit_Price); if (unitPrice < 0) throw publicError_('INVALID_PRICE','Unit price cannot be negative.'); const commissionRate = record.commissionRateOverride != null ? Number(record.commissionRateOverride) : Number(market.Commission_Rate); const gross = quantity * unitPrice; const revenue = gross * commissionRate; return [existingId || ('CE-' + Utilities.formatDate(new Date(), 'Etc/UTC', 'yyyyMMdd-HHmmss-') + Utilities.getUuid().slice(0,8)), existingTimestamp || new Date().toISOString(), record.serviceDate, 'Caribbean', market.Country, market.Country_Code, service.Service_Key, service.Service_Name, service.Service_Category, Number(service.Duration_Minutes) || '', quantity, unitPrice, service.Currency || market.Currency || 'USD', gross, commissionRate, revenue, gross - revenue, normalizeSource_(record.bookingSource), record.channel || 'Dashboard', record.enteredBy || 'Dashboard', record.status || 'valid', record.reviewReason || '', record.notes || '']; }
function mapSheet_(name) { const values = SpreadsheetApp.getActive().getSheetByName(name).getDataRange().getValues(); const headers = values.shift(); return values.filter(r => r.some(Boolean)).map(r => Object.fromEntries(headers.map((h,i)=>[h,r[i]]))); }
function activeByCode_(rows) { return rows.filter(r => String(r.Active).toLowerCase() !== 'false').reduce((m,r)=>(m[r.Country_Code]=r,m),{}); }
function serviceMap_(rows) { return rows.filter(r => String(r.Active).toLowerCase() !== 'false').reduce((m,r)=>(m[r.Country_Code + '|' + r.Service_Key]=r,m),{}); }
function lastRow_(){ const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.records); return Math.max(sheet.getLastRow()+1,2); }
function rowToRecord_(r){ return { id:r[0], timestamp:r[1], date:r[2], region:r[3], country:r[4], countryCode:r[5], serviceKey:r[6], serviceName:r[7], serviceCategory:r[8], durationMinutes:r[9], quantity:r[10], unitPrice:r[11], currency:r[12], grossSales:r[13], commissionRate:r[14], tranquilitasRevenue:r[15], partnerPayout:r[16], bookingSource:r[17], channel:r[18], sender:r[19], status:r[20], reviewReason:r[21], notes:r[22] }; }
function normalizeSource_(source){ return String(source || '').trim() || 'Other'; }
function validateToken_(token) { const expected = PropertiesService.getScriptProperties().getProperty('DASHBOARD_WRITE_TOKEN'); if (!expected || token !== expected) throw publicError_('UNAUTHORIZED','This dashboard is not authorized to write records.'); }
function publicError_(code, message){ const err = new Error(message); err.code = code; err.publicMessage = message; throw err; }
function json_(obj){ return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON); }
